# Generated by Django 4.2.13 on 2024-07-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='listuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='listuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='listuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='listuser',
            name='user_permissions',
        ),
    ]
