# Generated by Django 4.2.13 on 2024-07-20 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
